### PR TITLE
Add a Type Tag to Multi to selectively enable/disable it based on Context

### PR DESCRIPTION
**Pull request by JeremyRubin**
I think this approach is superior for the Multi tag as it makes Terminals constructed with a Tap context correct at compile time.

### CODE REVIEW

**Comment by JeremyRubin** [comment]
whoops forgot to commit a few files 😅

**Review by sanket1729 — COMMENTED** [review]
Strong ACK.
Thanks a lot. I will pick this commit to my PR later today. Somehow, I was assuming that this would leak into `Terminal` and `Miniscript`. 

It's a big plus that this change is local

**Comment by JeremyRubin** [comment]
I added another commit -- it's a bit "extra" safety at minimal cost that forces the implementors of ScriptContext to have to return either an Error or a Terminal. Not super valuable, but when the ! type gets stablized the Disabled element can be removed and then you can get irrefutable destructuring where appropriate...

But definitely more in the overkill category compared to the base commit.

**Comment by JeremyRubin** [comment]
closed as it's no longer needed as a PR for reviewing the concept

**Pull request closed without merging**
